version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=ivannikolaev'
      - 'POSTGRES_PASSWORD=Apolo'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=postgres'
  app:
    build: ./
    container_name: 'java-app'
    ports:
      - "8080:8080"
    links:
      - 'postgres:my-dataBase'

